export const links = [
  {
    slug: 'google',
    url: 'https://www.google.com',
    description: 'Search engine',
    active: true,
  },
  {
    slug: 'github',
    url: 'https://www.github.com',
    description: 'Code hosting platform',
    active: true,
  },
  {
    slug: 'reddit',
    url: 'https://www.reddit.com',
    description: 'Online community',
    active: false,
  },
  {
    slug: 'twitter',
    url: 'https://www.twitter.com',
    description: 'Social media platform',
    active: false,
  },
  {
    slug: 'amazon',
    url: 'https://www.amazon.com',
    description: 'Online marketplace',
    active: true,
  },
  {
    slug: 'youtube',
    url: 'https://www.youtube.com',
    description: 'Video sharing platform',
    active: false,
  },
  {
    slug: 'facebook',
    url: 'https://www.facebook.com',
    description: 'Social media platform',
    active: true,
  },
  {
    slug: 'stackoverflow',
    url: 'https://www.stackoverflow.com',
    description: 'Programming Q&A',
    active: true,
  },
  {
    slug: 'linkedin',
    url: 'https://www.linkedin.com',
    description: 'Professional networking',
    active: false,
  },
  {
    slug: 'wikipedia',
    url: 'https://www.wikipedia.org',
    description: 'Online encyclopedia',
    active: true,
  },
  {
    slug: 'instagram',
    url: 'https://www.instagram.com',
    description: 'Photo sharing platform',
    active: false,
  },
  {
    slug: 'netflix',
    url: 'https://www.netflix.com',
    description: 'Streaming service',
    active: true,
  },
  {
    slug: 'ebay',
    url: 'https://www.ebay.com',
    description: 'Online marketplace',
    active: false,
  },
  {
    slug: 'twitch',
    url: 'https://www.twitch.tv',
    description: 'Live streaming platform',
    active: true,
  },
  {
    slug: 'spotify',
    url: 'https://www.spotify.com',
    description: 'Music streaming service',
    active: false,
  },
  {
    slug: 'apple',
    url: 'https://www.apple.com',
    description: 'Technology company',
    active: true,
  },
  {
    slug: 'bing',
    url: 'https://www.bing.com',
    description: 'Search engine',
    active: true,
  },
  {
    slug: 'snapchat',
    url: 'https://www.snapchat.com',
    description: 'Photo messaging app',
    active: false,
  },
];
